# Generated by Django 3.0.8 on 2020-07-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
